### PR TITLE
Lower min required Python version to 3.7

### PR DESCRIPTION
**Pull request by donatasm**
Package could not be installed to Python `3.7` environments.

Lower the version to minimum supported, as stated in `attach` [docstring](https://github.com/scientific-python/lazy_loader/blob/d5a3e8299a9e9374763c9cf8e507935c724a5ad6/lazy_loader/__init__.py#L40).

### CODE REVIEW

**Comment by jarrodmillman** [comment]
@donatasm Thanks for the contribution! Before merging we should add 3.7 to the CI and classifiers. If you want to take care of it and see this soon, please:

- [ ] add 3.7 to the `classifiers` in `pyproject.toml`
- [ ] add 3.7 to the `python-version` in `.github/workflows/test.yml`
- [ ] change `args: [--py38-plus]` to `args: [--py37-plus]` in `.pre-commit-config.yaml`

If you don't respond in an hour or so, I will just push to your branch. Once that is done (assuming the tests pass), I will merge.

I plan to release `lazy_loader 0.1rc3` later today or tomorrow after doing a few other minor things.

**Comment by donatasm** [comment]
> @donatasm Thanks for the contribution! Before merging we should add 3.7 to the CI and classifiers. If you want to take care of it and see this soon, please:
> 
> * [ ]  add 3.7 to the `classifiers` in `pyproject.toml`
> * [ ]  add 3.7 to the `python-version` in `.github/workflows/test.yml`
> * [ ]  change `args: [--py38-plus]` to `args: [--py37-plus]` in `.pre-commit-config.yaml`
> 
> If you don't respond in an hour or so, I will just push to your branch. Once that is done (assuming the tests pass), I will merge.
> 
> I plan to release `lazy_loader 0.1rc3` later today or tomorrow after doing a few other minor things.

@jarrodmillman thanks, I'll fix it now.

**Comment by donatasm** [comment]
Done. All checks pass for Python 3.7! 🎉

**Comment by jarrodmillman** [comment]
Thanks!!

**Pull request merged**
