### PR TITLE
Warn when submodule attributes and submodule names conflict

### PR DESCRIPTION
**Pull request by stefanv**
Otherwise, it can be hard to predict what will be returned on
attribute access (probably the submodule).

This is in response to https://github.com/huggingface/huggingface_hub/pull/874#discussion_r873727353 on https://github.com/huggingface/huggingface_hub/pull/874

### CODE REVIEW

**Comment by adrinjalali** [comment]
I agree with the warning, but shouldn't we make sure the behavior here is the same as Python's non-lazy-loaded behavior? I agree the behavior is very unclear, but we probably want to not break people's code if they depend on Python's existing behavior ;)

**Comment by TortoiseHam** [comment]
For the record this did catch my project by surprise. We ended up having to rename many of our files to start with underscores to avoid the name conflicts

**Comment by stefanv** [comment]
@adrinjalali @TortoiseHam I agree that it would be ideal to avoid a change in behavior. I tried a fix with `sys.modules` yesterday, but failed.  I'll poke at it some more, but please let me know if you have ideas.

**Comment by stefanv** [comment]
Here's the problem:

> If an attribute is not found on a module object through the normal lookup (i.e. object.__getattribute__), then __getattr__ is searched in the module __dict__ before raising an AttributeError. 

`__getattribute__` returns the module, `__getattr__` returns the function.

**Pull request closed without merging**
